In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('finance_transactions.csv')

# Data Wrangling

In [3]:
df.head()

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
0,T00000001,21-02-2025,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.61,22.25,INR,Success,No,63,REF8835851139
1,T00000002,28-01-2023,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.56,16.84,INR,Success,No,21,REF9409811139
2,T00000003,25-06-2024,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.00,0.00,INR,Success,No,25,REF1704628312
3,T00000004,20-02-2025,A004122,C01357,Withdrawal,Auto Debit,Salary,4310.91,NaN,0.78,INR,Failed,No,43,REF3937614748
4,T00000005,06-08-2024,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.00,0.00,INR,Success,No,5,REF5855288886

In [4]:
df.tail()

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
50064,T00049879,01-09-2024,A006793,C02066,Transfer,Net Banking,Shopping,11386.50,22.77,4.10,INR,Success,No,31,REF6074582257
50065,T00049880,27-06-2025,A003754,C01053,Loan EMI,ATM,Entertainment,40959.94,81.92,14.75,INR,Success,No,17,REF4636170490
50066,T00049881,02-08-2024,A003657,C02434,Loan EMI,ATM,Education,9873.84,9.87,1.78,INR,Success,No,56,REF6815460792
50067,T00049882,13-11-2023,A003840,C03287,Transfer,UPI,Salary,13980.12,0.00,0.00,INR,Success,No,67,REF4683694384
50068,T00049883,25-02-2025,A007128,C03308,Bill Payment,Net Banking,Bank Charges,2780.85,2.78,0.50,INR,Success,No,25,REF4914886377

In [5]:
df.sample(10)

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
41010,T00041007,02-04-2023,A006930,C02685,Card Payment,UPI,Education,5511.70,0.00,0.00,INR,Failed,No,57,REF3432333320
36348,T00036345,22-08-2024,A001983,C03368,Loan EMI,Branch,Entertainment,2108.91,2.11,0.38,INR,Success,No,55,REF7717284240
36038,T00036035,28-08-2025,A001319,C02607,Withdrawal,Net Banking,Mutual Fund,2311.15,4.62,0.83,INR,Success,No,12,REF1547205256
31808,T00031805,21-08-2023,A004679,C01688,Refund,ATM,Entertainment,666.19,0.67,0.12,INR,Success,No,59,REF9482529671
38399,T00038396,21-08-2025,A000842,C00866,Card Payment,ATM,Insurance,4138.91,0.00,0.00,INR,Failed,No,52,REF4904244739
43033,T00043030,19-11-2025,A005939,C04154,Investment,Net Banking,Shopping,11350.54,56.75,10.21,INR,Success,No,15,REF3849620847
19622,T00019619,25-06-2025,A005889,C02329,Transfer,Net Banking,Travel,6627.99,6.63,1.19,INR,Success,No,65,REF7438280216
39645,T00039642,22-09-2024,A000626,C01355,Loan EMI,Auto Debit,Salary,1413.76,0.00,0.00,INR,Success,No,12,REF1119678186
4309,T00004306,12-06-2024,A007940,C01031,Loan EMI,Branch,Shopping,3228.98,0.00,0.00,INR,Success,No,51,REF6884092458
19715,T00019712,26-06-2023,A004514,C03355,Loan EMI,POS,Travel,7970.53,0.00,0.00,INR,Success,No,65,REF3225876876

In [6]:
df.columns

Index(['transaction_id', 'transaction_date', 'account_id', 'customer_id',
       'transaction_type', 'channel', 'merchant_category', 'amount',
       'fee_amount', 'tax_amount', 'currency', 'transaction_status',
       'is_fraud', 'risk_score', 'reference_no'],
      dtype='object')

In [7]:
df.dtypes

transaction_id         object
transaction_date       object
account_id             object
customer_id            object
transaction_type       object
channel                object
merchant_category      object
amount                float64
fee_amount            float64
tax_amount            float64
currency               object
transaction_status     object
is_fraud               object
risk_score              int64
reference_no           object
dtype: object

In [8]:
df.isnull().sum()

transaction_id         0
transaction_date       0
account_id             0
customer_id            0
transaction_type       0
channel                0
merchant_category      0
amount                 0
fee_amount            24
tax_amount             0
currency               0
transaction_status     0
is_fraud               0
risk_score             0
reference_no           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(68)

In [10]:
df[df.duplicated()]

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
15,T00000014,10-08-2024,A004138,C00960,Loan EMI,UPI,Travel,9334.16,9.33,1.68,INR,Success,No,45,REF9776706632
67,T00000065,26-02-2023,A006060,C00103,Deposit,Net Banking,Shopping,6526.38,0.00,0.00,INR,Success,No,5,REF3244794918
139,T00000136,18-03-2026,A003806,C03104,Transfer,Net Banking,Salary,10693.90,10.69,1.92,INR,Success,No,19,REF1743695851
50004,T00049983,08-01-2025,A006536,C04304,Fee Charge,Mobile App,Utilities,526.47,0.00,0.00,INR,Failed,No,9,REF5564672654
50005,T00049984,27-12-2025,A001626,C02778,Deposit,Mobile App,Salary,6549.07,32.75,5.89,INR,Success,No,31,REF1016550212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50064,T00049879,01-09-2024,A006793,C02066,Transfer,Net Banking,Shopping,11386.50,22.77,4.10,INR,Success,No,31,REF6074582257
50065,T00049880,27-06-2025,A003754,C01053,Loan EMI,ATM,Entertainment,40959.94,81.92,14.75,INR,Success,No,17,REF4636170490
50066,T00049881,02-08-2024,A003657,C02434,Loan EMI,ATM,Education,9873.84,9.87,1.78,INR,Success,No,56,REF6815460792
50067,T00049882,13-11-2023,A003840,C03287,Transfer,UPI,Salary,13980.12,0.00,0.00,INR,Success,No,67,REF4683694384
50068,T00049883,25-02-2025,A007128,C03308,Bill Payment,Net Banking,Bank Charges,2780.85,2.78,0.50,INR,Success,No,25,REF4914886377

In [11]:
df2 = pd.read_csv("customers.csv")

In [12]:
df2.head()

,customer_id,fisrt_name,second_name,gender,date_of_birth,city,state,occupation,customer_segment,annual_income,join_date
0,C00001,Karan,Chopra,Male,09-10-1982,Kolkata,West Bengal,Retired,SME,988416.79,15-04-2021
1,C00002,Ishaan,Patel,Male,07-10-1983,Chandigarh,Chandigarh,Salaried,Premium,457149.28,06-04-2022
2,C00003,Krishna,Patel,Male,27-11-1989,Hyderabad,Telangana,Retired,Retail,378907.24,06-03-2026
3,C00004,Amit,Verma,Male,13-08-1970,Lucknow,Uttar Pradesh,Salaried,Retail,299085.16,16-07-2021
4,C00005,Reyansh,Jain,Female,07-02-1977,Ahmedabad,Gujarat,Freelancer,SME,775436.07,23-02-2023

In [13]:
df2.tail()

,customer_id,fisrt_name,second_name,gender,date_of_birth,city,state,occupation,customer_segment,annual_income,join_date
4995,C04996,Pari,Kapoor,Male,06-11-2002,Hyderabad,Telangana,Business Owner,Retail,279631.80,06-11-2021
4996,C04997,Rohan,Malhotra,Female,01-01-1975,Bhopal,Madhya Pradesh,Business Owner,Retail,869312.76,20-07-2022
4997,C04998,Ira,Agarwal,Female,10-12-1976,Lucknow,Uttar Pradesh,Self Employed,Premium,3571015.01,03-04-2021
4998,C04999,Sneha,Joshi,Female,03-04-1994,Kochi,Kerala,Salaried,SME,1046872.92,28-07-2023
4999,C05000,Anika,Patel,Female,26-11-2003,Nagpur,Maharashtra,Freelancer,Retail,1017717.21,25-04-2023

In [15]:
df2.sample(10)

,customer_id,fisrt_name,second_name,gender,date_of_birth,city,state,occupation,customer_segment,annual_income,join_date
195,C00196,Kiara,Bansal,Male,02-08-1995,Surat,Gujarat,Business Owner,Wealth,1971778.35,22-03-2022
2557,C02558,Aadhya,Malhotra,Male,02-11-1988,Chandigarh,Chandigarh,Retired,Retail,470466.45,22-05-2022
2349,C02350,Krishna,Kapoor,Female,21-08-1960,Pune,Maharashtra,Business Owner,Retail,566633.00,06-09-2020
1474,C01475,Kabir,Gupta,Female,23-10-1986,Pune,Maharashtra,Student,Retail,471965.73,06-05-2018
2103,C02104,Reyansh,Bansal,Female,18-10-2000,Bhopal,Madhya Pradesh,Student,Retail,767490.75,20-05-2019
3487,C03488,Priya,Kulkarni,Female,19-09-1963,Gurugram,Haryana,Retired,SME,754438.38,15-01-2018
793,C00794,Sneha,Iyer,Female,22-07-1992,Indore,Madhya Pradesh,Self Employed,Retail,385298.61,21-10-2024
3949,C03950,Rohan,Joshi,Male,15-04-2001,Mysuru,Karnataka,Business Owner,Retail,247658.49,23-05-2024
274,C00275,Myra,Verma,Male,15-11-1972,Bengaluru,Karnataka,Retired,SME,863385.56,10-11-2022
2260,C02261,Anaya,Kulkarni,Female,28-04-1981,Coimbatore,Tamil Nadu,Retired,Retail,199852.14,28-04-2018

In [16]:
df2.isnull().sum()

customer_id         0
fisrt_name          0
second_name         0
gender              0
date_of_birth       0
city                0
state               0
occupation          0
customer_segment    0
annual_income       0
join_date           0
dtype: int64

In [18]:
df2.duplicated().sum()

np.int64(0)

In [19]:
df2.dtypes

customer_id          object
fisrt_name           object
second_name          object
gender               object
date_of_birth        object
city                 object
state                object
occupation           object
customer_segment     object
annual_income       float64
join_date            object
dtype: object

In [20]:
df2.columns

Index(['customer_id', 'fisrt_name', 'second_name', 'gender', 'date_of_birth',
       'city', 'state', 'occupation', 'customer_segment', 'annual_income',
       'join_date'],
      dtype='object')

# Data Clening

In [22]:
df['fee_amount'].isna().sum()

np.int64(24)

In [24]:
df['fee_amount'] = df['fee_amount'].fillna(df['fee_amount'].mean())

In [26]:
df['currency'] = df['currency'].str.upper()

In [31]:
df['transaction_date'] = df['transaction_date'].astype('datetime64[ns]')

In [33]:
df2.dtypes

customer_id          object
fisrt_name           object
second_name          object
gender               object
date_of_birth        object
city                 object
state                object
occupation           object
customer_segment     object
annual_income       float64
join_date            object
dtype: object

In [37]:
df2[['join_date' , 'date_of_birth']] = df2[['join_date' , 'date_of_birth']].astype('datetime64[ns]')

In [38]:
df2.dtypes

customer_id                 object
fisrt_name                  object
second_name                 object
gender                      object
date_of_birth       datetime64[ns]
city                        object
state                       object
occupation                  object
customer_segment            object
annual_income              float64
join_date           datetime64[ns]
dtype: object

In [43]:
df2.rename(columns={'fisrt_name' :'first_name'} , inplace=True)

In [45]:
df2['customer_name'] = df2['first_name'] + " " + df2['second_name']

In [48]:
df2.drop(columns=['first_name' , 'second_name'] , inplace=True)

In [49]:
df2

,customer_id,gender,date_of_birth,city,state,occupation,customer_segment,annual_income,join_date,customer_name
0,C00001,Male,1982-09-10,Kolkata,West Bengal,Retired,SME,988416.79,2021-04-15,Karan Chopra
1,C00002,Male,1983-07-10,Chandigarh,Chandigarh,Salaried,Premium,457149.28,2022-06-04,Ishaan Patel
2,C00003,Male,1989-11-27,Hyderabad,Telangana,Retired,Retail,378907.24,2026-06-03,Krishna Patel
3,C00004,Male,1970-08-13,Lucknow,Uttar Pradesh,Salaried,Retail,299085.16,2021-07-16,Amit Verma
4,C00005,Female,1977-07-02,Ahmedabad,Gujarat,Freelancer,SME,775436.07,2023-02-23,Reyansh Jain
...,...,...,...,...,...,...,...,...,...,...
4995,C04996,Male,2002-06-11,Hyderabad,Telangana,Business Owner,Retail,279631.80,2021-06-11,Pari Kapoor
4996,C04997,Female,1975-01-01,Bhopal,Madhya Pradesh,Business Owner,Retail,869312.76,2022-07-20,Rohan Malhotra
4997,C04998,Female,1976-10-12,Lucknow,Uttar Pradesh,Self Employed,Premium,3571015.01,2021-03-04,Ira Agarwal
4998,C04999,Female,1994-03-04,Kochi,Kerala,Salaried,SME,1046872.92,2023-07-28,Sneha Joshi
4999,C05000,Female,2003-11-26,Nagpur,Maharashtra,Freelancer,Retail,1017717.21,2023-04-25,Anika Patel

In [50]:
df

,transaction_id,transaction_date,account_id,customer_id,transaction_type,channel,merchant_category,amount,fee_amount,tax_amount,currency,transaction_status,is_fraud,risk_score,reference_no
0,T00000001,2025-02-21,A001795,C00629,Investment,Mobile App,Food Delivery,24721.24,123.610000,22.25,INR,Success,No,63,REF8835851139
1,T00000002,2023-01-28,A004859,C02038,Transfer,UPI,Groceries,18711.77,93.560000,16.84,INR,Success,No,21,REF9409811139
2,T00000003,2024-06-25,A003081,C00652,Transfer,Net Banking,Groceries,45865.90,0.000000,0.00,INR,Success,No,25,REF1704628312
3,T00000004,2025-02-20,A004122,C01357,Withdrawal,Auto Debit,Salary,4310.91,14.528805,0.78,INR,Failed,No,43,REF3937614748
4,T00000005,2024-06-08,A004150,C02547,Deposit,Branch,Shopping,11646.45,0.000000,0.00,INR,Success,No,5,REF5855288886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50064,T00049879,2024-01-09,A006793,C02066,Transfer,Net Banking,Shopping,11386.50,22.770000,4.10,INR,Success,No,31,REF6074582257
50065,T00049880,2025-06-27,A003754,C01053,Loan EMI,ATM,Entertainment,40959.94,81.920000,14.75,INR,Success,No,17,REF4636170490
50066,T00049881,2024-02-08,A003657,C02434,Loan EMI,ATM,Education,9873.84,9.870000,1.78,INR,Success,No,56,REF6815460792
50067,T00049882,2023-11-13,A003840,C03287,Transfer,UPI,Salary,13980.12,0.000000,0.00,INR,Success,No,67,REF4683694384
50068,T00049883,2025-02-25,A007128,C03308,Bill Payment,Net Banking,Bank Charges,2780.85,2.780000,0.50,INR,Success,No,25,REF4914886377

# Creating New Table

In [52]:
start_date = df['transaction_date'].min()
end_date = df['transaction_date'].max()
all_dates = pd.date_range(df['transaction_date'].min() , df['transaction_date'].max() , freq='D')

In [53]:
calender = pd.DataFrame({'Date' : all_dates})

In [56]:
calender

           Date
0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
...         ...
1429 2026-11-30
1430 2026-12-01
1431 2026-12-02
1432 2026-12-03
1433 2026-12-04

[1434 rows x 1 columns]